// This file was auto-generated by extract-pure-functions.js
// Source file: docs/script.js
// Generated at: 2026-01-01T15:07:39.470Z

export const PRIMES = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37];

export function getDivisorPairs(n) {
    const pairs = [];
    for (let i = 2; i <= Math.sqrt(n); i++) {
        if (n % i === 0) {
            pairs.push([i, n / i]);
        }
    }
    return pairs;
}

export function selectWeightedPrime() {
    // 重み: 2, 3, 5, 7を特に高確率に
    const weights = [25, 20, 15, 12, 3, 2, 1, 1, 1, 1, 1, 1];
    const totalWeight = weights.reduce((a, b) => a + b, 0);
    let random = Math.random() * totalWeight;
    
    for (let i = 0; i < PRIMES.length; i++) {
        random -= weights[i];
        if (random <= 0) {
            return PRIMES[i];
        }
    }
    return PRIMES[0];
}

export function getStopProbability(value) {
    if (value < 20) {
        return 0; // 20未満は続ける
    } else if (value <= 40) {
        return 0.3; // 20〜40は30%で停止
    } else if (value <= 60) {
        return 0.5; // 40〜60は50%で停止
    } else if (value <= 80) {
        return 0.6; // 60〜80は60%で停止
    } else if (value <= 120) {
        return 0.75; // 80〜120は75%で停止
    } else {
        return 1.0; // それ以上は100%で停止
    }
}

export function generateAnswerNumber(maxValue = 150) {
    let result = selectWeightedPrime();
    const divisors = [result];
    let retry = 0;
    
    while (divisors.length < 5) {
        const prime = selectWeightedPrime();
        const newResult = result * prime;
        
        // 上限を超えたら終了
        if (newResult > maxValue) {
            if (divisors.length < 2) {
                result *= [2, 3][Math.floor(Math.random() * 2)];
            }else if (retry < 3){
                retry++;
                continue;
            }
            break;
        }
        
        result = newResult;
        divisors.push(result);
        
        // 現在の値に応じて停止するかどうかを判定
        if (Math.random() < getStopProbability(result)) {
            break;
        }
    }
    
    return result;
}

export function generateWrongChoices(targetNumber) {
    // 候補となる数値の配列を生成（3以下とtargetNumberは除外）
    const candidates = [];
    for (let offset = -10; offset <= 10; offset++) {
        const nearbyNumber = targetNumber + offset;
        if (nearbyNumber > 3 && nearbyNumber !== targetNumber) {
            candidates.push(nearbyNumber);
        }
    }
    shuffleArray(candidates);
    // targetNumberが奇数の場合、奇数を優先的に選ぶ
    if (targetNumber % 2 === 1) {
        candidates.sort((a, b) => (a % 2 === 0) - (b % 2 === 0));
    }
    
    // 候補から順に約数ペアを取得
    const wrongChoices = [];
    for (const nearbyNumber of candidates) {
        if (wrongChoices.length >= 3) break;
        
        const pairs = getDivisorPairs(nearbyNumber);
        if (pairs.length === 0) continue;
        
        const selectedPair = pairs[Math.floor(Math.random() * pairs.length)];
        wrongChoices.push(selectedPair);
    }
    
    return wrongChoices;
}

export function shuffleArray(array) {
    const shuffled = array
        .map(value => ({ value, rand: Math.random() }))
        .sort((a, b) => a.rand - b.rand);
    for (let i = 0; i < array.length; i++) {
        array[i] = shuffled[i].value;
    }
    return array;
}
